### PR TITLE
refactor(Dashboard Today Tasks): use GridStack instead of imbricated …

### PR DESCRIPTION
**Pull request by renaudjenny**
…ForEach

### CODE REVIEW

**Comment by renaudjenny** [comment]
I'm sorry @TheVaan and @Dimillian I wasn't able to figure it out why it's crashing while opening the list. The only thing I provided is a working `GridStack` for Todays Tasks.

I've some suspicions the cause could be a race condition of the UserCollection shared instance.

What I found:
if you replace
```swift
.onTapGesture {
    self.sheet = .customTasks(collection: self.collection)
}
```
by
```swift
.onTapGesture {
    self.sheet = .customTasks(collection: UserCollection.shared)
}
```
There is no crash while opening the `CustomTasksListView` but the save crashes although :(.

**Comment by Dimillian** [comment]
I’ll take a look tomorrow :)

**Comment by TheVaan** [comment]
I’ll take a look on it later. 
Let’s double check that.

**Comment by TheVaan** [comment]
Well, code looks really good. I don’t see changes that could cause your problems 🧐 but before, there were no problems with opening CustomTaskListView and/or saving 🤔
I hope @Dimillian can find the Problem 😕

**Pull request merged**
